seed: 42
max_layer_num: 52
num_inference_steps: 28

lora_rank: 64
lora_alpha: 64
lora_dropout: 0

max_steps: 200000
log_every: 1000
save_every: 1000
max_sequence_length: 512
cfg: 4.0
accum_steps: 4
optimizer: Prodigy

adapter_scale: 0.9

data_dir: "/workspace/dataset/cld_dataset/snapshots/snapshot_1"
caption_mapping: "/workspace/ShuoIsAllYouNeed/Yao/final/CLD/caption_formal.json"  # Optional: path to LLaVA-generated captions

artplus_lora_dir: "/workspace/ShuoIsAllYouNeed/Yao/final/CLD/ckpt/prism_ft_LoRA"
resume_from: "/workspace/ShuoIsAllYouNeed/Yao/final/CLD/ckpt/decouple_LoRA"

pretrained_model_name_or_path: "flux_model"
pretrained_adapter_path: "Path_to_pretrained_FLUX_adapter"
pretrained_lora_dir: "ckpt/pre_trained_LoRA"
output_dir: "FT_on_Crello_ckpt"